### ISSUE TITLE
Missing files & Naive and BLAST predictor

### ISSUE THREAD

**Issue by gioodm** [BioComputingUP/CAFA-evaluator#12]
In the Wiki, the links to the files from previous CAFA challenges do not lead to actual files. How can I gain access to those?

Also, is there an easy way to obtain the Fmax, Smin and AUPCR of the Naive and BLAST predictors using this repo?  Similar to what is explained in the Matlab repo https://github.com/yuxjiang/CAFA2 "How to build baseline predictors"?

Thanks in advance.

**Comment by damianopiovesan** [comment]
Thanks, I've fixed the links to previous CAFA challenges in the Wiki.

For what regards baselines predictions they are not provided by the CAFA organizers. They can be generated using the sofware you referenced or by hand. Once you have the predictions, you can use this tool to calculate F-max, S-min, etc. 

Please note that for weighted metrics, including semantic similarity, you also need an "Information Accretion" file. You can generate it using the code in the [InformationAccretion](https://github.com/claradepaolis/InformationAccretion) repo.

**Comment by gioodm** [comment]
Thank you very much for the fast reply and the resources! 

When calculating the Information Accretion, should the dataset of GO annotations on which it is calculated (in the GitHub repo you shared referred to as: terms.tsv) include only the terms in the ground truth labels or also the ones predicted by my predictor?

**Comment by damianopiovesan** [comment]
CAFA-evaluation will only assess terms present in the ground truth (terms.tsv in your case) AND in the IA file. It's important to be aware that the ground truth file typically includes only the leaf terms and not their ancestors. Therefore, I recommend calculating IA for all terms to ensure comprehensive coverage.

In the [data](https://www.kaggle.com/competitions/cafa-5-protein-function-prediction/data) section of the CAFA5 Kaggle challenge, you can find a precalculated IA file. However, keep in mind that it was calculated based on a specific version of the Gene Ontology and SwissProt. It may be necessary to recalculate IA if you are using a different version.
