### ISSUE TITLE
How to evaluate partial-knowledge proteins

### ISSUE THREAD

**Issue by Siri101** [BioComputingUP/CAFA-evaluator#14]
When we evaluate partial-knowledge proteins, how to handle the annotations in training set?

**Comment by damianopiovesan** [comment]
Hello,

The CAFA-evaluator is designed to be agnostic to the training methods used. The responsibility for removing overlaps between training and test data lies with you. You can do this in two ways, by filtering the ground truth dataset; or by filtering the training examples

Regarding partial-knowledge evaluation, it's important to consider different namespaces independently. For example it's fair to evaluate an MFO prediction for a protein that included BPO or CCO terms in your training, but not MFO terms.
