### ISSUE TITLE
bug in f calculation

### ISSUE THREAD

**Issue by kad-ecoli** [BioComputingUP/CAFA-evaluator#9]
Currently, this evaluator will ignore all terms with information content (i.e, information accretion) =0.
While this is perfectly fine for wFmax, it does not generate correct result for Fmax. 

For Fmax calculation, only root terms should be excluded. All other GO terms, including those with information accretion of 0, should be considered.

**Comment by damianopiovesan** [comment]
Hi Chengxin,

I've pushed a fix to a new branch ("ia_fix"). This modification should not affect the Kaggle results, except maybe for a scaling factor. Indeed, the normalization in Kaggle is done by the number of proteins in the ground truth, without removing those proteins with IA = 0 for all annotations. 
I'll be discussing with the other organizers whether we should also update the code in Kaggle.

**Comment by kad-ecoli** [comment]
Yes, I see you have fixed the bug on Smin calculation reported on the other thread.

However, for this thread, my concern is on GO terms with IA=0, not proteins with IA=0. For proteins with both IA=0 GO terms and IA>0 GO terms, both kinds of GO terms should be included so long as they are not root terms.
